USE [master]
GO
/****** Object:  Database [SSKMS]    Script Date: 21/05/2023 1:19:26 PM ******/
CREATE DATABASE [SSKMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SSKMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SSKMS.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SSKMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SSKMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SSKMS] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SSKMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SSKMS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SSKMS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SSKMS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SSKMS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SSKMS] SET ARITHABORT OFF 
GO
ALTER DATABASE [SSKMS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SSKMS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SSKMS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SSKMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SSKMS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SSKMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SSKMS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SSKMS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SSKMS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SSKMS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SSKMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SSKMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SSKMS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SSKMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SSKMS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SSKMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SSKMS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SSKMS] SET RECOVERY FULL 
GO
ALTER DATABASE [SSKMS] SET  MULTI_USER 
GO
ALTER DATABASE [SSKMS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SSKMS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SSKMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SSKMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SSKMS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SSKMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SSKMS', N'ON'
GO
ALTER DATABASE [SSKMS] SET QUERY_STORE = ON
GO
ALTER DATABASE [SSKMS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SSKMS]
GO
/****** Object:  User [dib]    Script Date: 21/05/2023 1:19:26 PM ******/
CREATE USER [dib] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [dib]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [dib]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [dib]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [dib]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [dib]
GO
ALTER ROLE [db_datareader] ADD MEMBER [dib]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [dib]
GO
ALTER ROLE [db_denydatareader] ADD MEMBER [dib]
GO
ALTER ROLE [db_denydatawriter] ADD MEMBER [dib]
GO
/****** Object:  Table [dbo].[APPLICATION]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPLICATION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_Application] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APPLICATION_BELONGS_TO_PARADIGM]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPLICATION_BELONGS_TO_PARADIGM](
	[APPLICATION_ID] [int] NOT NULL,
	[SOFTWARE_PARADIGM] [int] NOT NULL,
 CONSTRAINT [PK_APPLICATION_BELONGS_TO_PARADIGM] PRIMARY KEY CLUSTERED 
(
	[APPLICATION_ID] ASC,
	[SOFTWARE_PARADIGM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APPLICATION_BELONGS_TO_SUBJECT_AREA]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPLICATION_BELONGS_TO_SUBJECT_AREA](
	[APPLICATION_ID] [int] NOT NULL,
	[SUBJECT_AREA_ID] [int] NOT NULL,
 CONSTRAINT [PK_APPLICATION_BELONGS_TO_SUBJECT_AREA] PRIMARY KEY CLUSTERED 
(
	[APPLICATION_ID] ASC,
	[SUBJECT_AREA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APPLICATION_HAS_SOFTWARE_FEATURE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPLICATION_HAS_SOFTWARE_FEATURE](
	[APPLICATION_ID] [int] NOT NULL,
	[SOFTWARE_FEATURE_ID] [int] NOT NULL,
 CONSTRAINT [PK_APPLICATION_HAS_SOFTWARE_FEATURE] PRIMARY KEY CLUSTERED 
(
	[APPLICATION_ID] ASC,
	[SOFTWARE_FEATURE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APPLICATION_USES_LANGUAGE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPLICATION_USES_LANGUAGE](
	[APPLICATION_ID] [int] NOT NULL,
	[LANGUAGE_ID] [int] NOT NULL,
 CONSTRAINT [PK_APPLICATION_USES_LANGUAGE] PRIMARY KEY CLUSTERED 
(
	[APPLICATION_ID] ASC,
	[LANGUAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APPLICATION_USES_SYSTEM_STRUCTURE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPLICATION_USES_SYSTEM_STRUCTURE](
	[APPLICATION_ID] [int] NOT NULL,
	[SYSTEM_STRUCTURE_ID] [int] NOT NULL,
 CONSTRAINT [PK_APPLICATION_USES_SYSTEM_STRUCTURE] PRIMARY KEY CLUSTERED 
(
	[APPLICATION_ID] ASC,
	[SYSTEM_STRUCTURE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APPROACH]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPROACH](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_APPROACH] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APPROACH_HAS_TECHNIQUE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPROACH_HAS_TECHNIQUE](
	[APPROACH_ID] [int] NOT NULL,
	[TECHNIQUE_ID] [int] NOT NULL,
 CONSTRAINT [PK_APPROACH_HAS_TECHNIQUE] PRIMARY KEY CLUSTERED 
(
	[APPROACH_ID] ASC,
	[TECHNIQUE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[APPROACH_RELATED_STRUCTURE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPROACH_RELATED_STRUCTURE](
	[APPROACH_ID] [int] NOT NULL,
	[SYSTEM_STRUCTURE_ID] [int] NOT NULL,
 CONSTRAINT [PK_APPROACH_RELATED_STRUCTURE] PRIMARY KEY CLUSTERED 
(
	[APPROACH_ID] ASC,
	[SYSTEM_STRUCTURE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONSTRUCTION_PRACTICE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONSTRUCTION_PRACTICE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_CONSTRUCTION_PRACTICE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONSTRUCTION_PRACTICE_FOLLOWS_STRATEGY]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONSTRUCTION_PRACTICE_FOLLOWS_STRATEGY](
	[CONSTRUCTION_PRACTICE_ID] [int] NOT NULL,
	[STRATEGY_ID] [int] NOT NULL,
 CONSTRAINT [PK_CONSTRUCTION_PRACTICE_FOLLOWS_STRATEGY] PRIMARY KEY CLUSTERED 
(
	[CONSTRUCTION_PRACTICE_ID] ASC,
	[STRATEGY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONSTRUCTION_PRACTICE_HAS_METHOD]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONSTRUCTION_PRACTICE_HAS_METHOD](
	[CONSTRUCTION_PRACTICE_ID] [int] NOT NULL,
	[METHOD_ID] [int] NOT NULL,
 CONSTRAINT [PK_CONSTRUCTION_PRACTICE_HAS_METHOD] PRIMARY KEY CLUSTERED 
(
	[CONSTRUCTION_PRACTICE_ID] ASC,
	[METHOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LANGUAGE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LANGUAGE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_LANGUAGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LANGUAGE_HAS_SECURITY_TOOL]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LANGUAGE_HAS_SECURITY_TOOL](
	[LANGUAGE_ID] [int] NOT NULL,
	[SECURITY_TOOL] [int] NOT NULL,
 CONSTRAINT [PK_LANGUAGE_HAS_SECURITY_TOOL] PRIMARY KEY CLUSTERED 
(
	[LANGUAGE_ID] ASC,
	[SECURITY_TOOL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LANGUAGE_PROVIDES_TECHNOLOGY]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LANGUAGE_PROVIDES_TECHNOLOGY](
	[LANGUAGE_ID] [int] NOT NULL,
	[TECHNOLOGY_ID] [int] NOT NULL,
 CONSTRAINT [PK_LANGUAGE_PROVIDES_TECHNOLOGY] PRIMARY KEY CLUSTERED 
(
	[LANGUAGE_ID] ASC,
	[TECHNOLOGY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MECHANISM]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MECHANISM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_MECHANISM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MECHANISM_UTILIZES_SECURITY_TOOL]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MECHANISM_UTILIZES_SECURITY_TOOL](
	[MECHANISM_ID] [int] NOT NULL,
	[SECURITY_TOOL_ID] [int] NOT NULL,
 CONSTRAINT [PK_MECHANISM_UTILIZES_SECURITY_TOOL] PRIMARY KEY CLUSTERED 
(
	[MECHANISM_ID] ASC,
	[SECURITY_TOOL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[METHOD]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[METHOD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_METHOD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[METHOD_HAS_MECHANISM]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[METHOD_HAS_MECHANISM](
	[METHOD_ID] [int] NOT NULL,
	[MECHANISM_ID] [int] NOT NULL,
 CONSTRAINT [PK_METHOD_HAS_MECHANISM] PRIMARY KEY CLUSTERED 
(
	[METHOD_ID] ASC,
	[MECHANISM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[METHOD_RELATED_LANGUAGE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[METHOD_RELATED_LANGUAGE](
	[METHOD_ID] [int] NOT NULL,
	[LANGUAGE_ID] [int] NOT NULL,
 CONSTRAINT [PK_METHOD_RELATED_LANGUAGE] PRIMARY KEY CLUSTERED 
(
	[METHOD_ID] ASC,
	[LANGUAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SECURITY_ERROR]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECURITY_ERROR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_SECURITY_ERROR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS](
	[SECURITY_ERROR_ID] [int] NOT NULL,
	[SOFTWARE_WEAKNESS_ID] [int] NOT NULL,
 CONSTRAINT [PK_SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS] PRIMARY KEY CLUSTERED 
(
	[SECURITY_ERROR_ID] ASC,
	[SOFTWARE_WEAKNESS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SECURITY_ERROR_MITIGATED_BY_CONSTRUCTION_PRACTICE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECURITY_ERROR_MITIGATED_BY_CONSTRUCTION_PRACTICE](
	[SECURITY_ERROR_ID] [int] NOT NULL,
	[CONSTRUCTION_PRACTICE_ID] [int] NOT NULL,
 CONSTRAINT [PK_SECURITY_ERROR_MITIGATED_BY_CONSTRUCTION_PRACTICE] PRIMARY KEY CLUSTERED 
(
	[SECURITY_ERROR_ID] ASC,
	[CONSTRUCTION_PRACTICE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SECURITY_ERROR_SPOTTED_BY_VERIFICATION_PRACTICE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECURITY_ERROR_SPOTTED_BY_VERIFICATION_PRACTICE](
	[SECURITY_ERROR_ID] [int] NOT NULL,
	[VERIFICATION_PRACTICE_ID] [int] NOT NULL,
 CONSTRAINT [PK_SECURITY_ERROR_SPOTTED_BY_VERIFICATION_PRACTICE] PRIMARY KEY CLUSTERED 
(
	[SECURITY_ERROR_ID] ASC,
	[VERIFICATION_PRACTICE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SECURITY_REQUIREMENT]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECURITY_REQUIREMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_SECURITY_REQUIRMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SECURITY_REQUIREMENT_ASSOCIATED_SECURITY_ERROR]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECURITY_REQUIREMENT_ASSOCIATED_SECURITY_ERROR](
	[SECURITY_REQUIREMENT_ID] [int] NOT NULL,
	[SECURITY_ERROR_ID] [int] NOT NULL,
 CONSTRAINT [PK_SECURITY_REQUIREMENT_ASSOCIATED_SECURITY_ERROR] PRIMARY KEY CLUSTERED 
(
	[SECURITY_REQUIREMENT_ID] ASC,
	[SECURITY_ERROR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_CONSTRUCTION_PRACTICE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_CONSTRUCTION_PRACTICE](
	[SECURITY_REQUIREMENT_ID] [int] NOT NULL,
	[CONSTRUCTION_PRACTICE_ID] [int] NOT NULL,
 CONSTRAINT [PK_SECURITY_REQUIREMENT_FOLLOWED_BY_CONSTRUCTION_PRACTICE] PRIMARY KEY CLUSTERED 
(
	[SECURITY_REQUIREMENT_ID] ASC,
	[CONSTRUCTION_PRACTICE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_VERIFICATION_PRACTICE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_VERIFICATION_PRACTICE](
	[SECURITY_REQUIREMENT_ID] [int] NOT NULL,
	[VERIFICATION_PRACTICE_ID] [int] NOT NULL,
 CONSTRAINT [PK_SECURITY_REQUIREMENT_FOLLOWED_BY_VERIFICATION_PRACTICE] PRIMARY KEY CLUSTERED 
(
	[SECURITY_REQUIREMENT_ID] ASC,
	[VERIFICATION_PRACTICE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SECURITY_TOOL]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECURITY_TOOL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_SECURITY_TOOL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOFTWARE_FEATURE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOFTWARE_FEATURE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_SOFTWARE_FEATURE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOFTWARE_FEATURE_HAS_CONSTRUCTION_PRACTICE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOFTWARE_FEATURE_HAS_CONSTRUCTION_PRACTICE](
	[SOFTWARE_FEATURE_ID] [int] NOT NULL,
	[CONSTRUCTION_PRACTICE_ID] [int] NOT NULL,
 CONSTRAINT [PK_SOFTWARE_FEATURE_HAS_CONTRUCTION_PRACTICE] PRIMARY KEY CLUSTERED 
(
	[SOFTWARE_FEATURE_ID] ASC,
	[CONSTRUCTION_PRACTICE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOFTWARE_FEATURE_HAS_SECURITY_REQUIREMENT]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOFTWARE_FEATURE_HAS_SECURITY_REQUIREMENT](
	[SOFTWARE_FEATURE_ID] [int] NOT NULL,
	[SECURITY_REQUIREMENT_ID] [int] NOT NULL,
 CONSTRAINT [PK_SOFTWARE_FEATURE_HAS_SECURITY_REQUIREMENT] PRIMARY KEY CLUSTERED 
(
	[SOFTWARE_FEATURE_ID] ASC,
	[SECURITY_REQUIREMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOFTWARE_PARADIGM]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOFTWARE_PARADIGM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_SOFTWARE_PARADIGM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOFTWARE_PARADIGM_HAS_LANGUAGE_OPTION]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOFTWARE_PARADIGM_HAS_LANGUAGE_OPTION](
	[SOFTWARE_PARADIGM_ID] [int] NOT NULL,
	[LANGUAGE_ID] [int] NOT NULL,
 CONSTRAINT [PK_SOFTWARE_PARADIGM_HAS_LANGUAGE_OPTION] PRIMARY KEY CLUSTERED 
(
	[SOFTWARE_PARADIGM_ID] ASC,
	[LANGUAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOFTWARE_PARADIGM_HAS_SOFTWARE_FEATURE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOFTWARE_PARADIGM_HAS_SOFTWARE_FEATURE](
	[SOFTWARE_PARADIGM_ID] [int] NOT NULL,
	[SOFTWARE_FEATURE_ID] [int] NOT NULL,
 CONSTRAINT [PK_SOFTWARE_PARADIGM_HAS_FEATURE] PRIMARY KEY CLUSTERED 
(
	[SOFTWARE_PARADIGM_ID] ASC,
	[SOFTWARE_FEATURE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOFTWARE_WEAKNESS]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOFTWARE_WEAKNESS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_SOFTWARE_WEAKNESS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STRATEGY]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STRATEGY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_STRATEGY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUBJECT_AREA]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUBJECT_AREA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_SUBJECT_AREA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUBJECT_AREA_HAS_SOFTWARE_FEATURE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUBJECT_AREA_HAS_SOFTWARE_FEATURE](
	[SUBJECT_AREA_ID] [int] NOT NULL,
	[SOFTWARE_FEATURE_ID] [int] NOT NULL,
 CONSTRAINT [PK_SUBJECT_AREA_HAS_SOFTWARE_FEATURE] PRIMARY KEY CLUSTERED 
(
	[SUBJECT_AREA_ID] ASC,
	[SOFTWARE_FEATURE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYSTEM_STRUCTURE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYSTEM_STRUCTURE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_SYSTEM_STRUCTURE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TECHNIQUE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TECHNIQUE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_TECHNIQUE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TECHNIQUE_HAS_SECURITY_TOOL]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TECHNIQUE_HAS_SECURITY_TOOL](
	[TECHNIQUE_ID] [int] NOT NULL,
	[SECURITY_TOOL_ID] [int] NOT NULL,
 CONSTRAINT [PK_TECHNIQUE_HAS_SECURITY_TOOL] PRIMARY KEY CLUSTERED 
(
	[TECHNIQUE_ID] ASC,
	[SECURITY_TOOL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TECHNOLOGY]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TECHNOLOGY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_TECHNOLOGY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TECHNOLOGY_HAS_SECURITY_TOOL]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TECHNOLOGY_HAS_SECURITY_TOOL](
	[TECHNOLOGY_ID] [int] NOT NULL,
	[SECURITY_TOOL_ID] [int] NOT NULL,
 CONSTRAINT [PK_TECHNOLOGY_HAS_SECURITY_TOOL] PRIMARY KEY CLUSTERED 
(
	[TECHNOLOGY_ID] ASC,
	[SECURITY_TOOL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TECHNOLOGY_RELATED_STRUCTURE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TECHNOLOGY_RELATED_STRUCTURE](
	[TECHNOLOGY_ID] [int] NOT NULL,
	[SYSTEM_STRUCTURE_ID] [int] NOT NULL,
 CONSTRAINT [PK_TECHNOLOGY_RELATED_STRUCTURE] PRIMARY KEY CLUSTERED 
(
	[TECHNOLOGY_ID] ASC,
	[SYSTEM_STRUCTURE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VERIFICATION_PRACTICE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VERIFICATION_PRACTICE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_VERIFICATION_PRACTICE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VERIFICATION_PRACTICE_HAS_APPROACH]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VERIFICATION_PRACTICE_HAS_APPROACH](
	[VERIFICATION_PRACTICE_ID] [int] NOT NULL,
	[APPROACH_ID] [int] NOT NULL,
 CONSTRAINT [PK_VERIFICATION_PRACTICE_HAS_APPROACH] PRIMARY KEY CLUSTERED 
(
	[VERIFICATION_PRACTICE_ID] ASC,
	[APPROACH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VERIFICATION_PRACTICE_HAS_TECHNIQUE]    Script Date: 21/05/2023 1:19:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VERIFICATION_PRACTICE_HAS_TECHNIQUE](
	[VERIFICATION_PRACTICE_ID] [int] NOT NULL,
	[TECHNIQUE_ID] [int] NOT NULL,
 CONSTRAINT [PK_VERIFICATION_PRACTICE_HAS_TECHNIQUE] PRIMARY KEY CLUSTERED 
(
	[VERIFICATION_PRACTICE_ID] ASC,
	[TECHNIQUE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[APPLICATION_BELONGS_TO_PARADIGM]  WITH CHECK ADD  CONSTRAINT [FK_APPLICATION_ID] FOREIGN KEY([APPLICATION_ID])
REFERENCES [dbo].[APPLICATION] ([ID])
GO
ALTER TABLE [dbo].[APPLICATION_BELONGS_TO_PARADIGM] CHECK CONSTRAINT [FK_APPLICATION_ID]
GO
ALTER TABLE [dbo].[APPLICATION_BELONGS_TO_PARADIGM]  WITH CHECK ADD  CONSTRAINT [FK_PARADIGM_ID] FOREIGN KEY([SOFTWARE_PARADIGM])
REFERENCES [dbo].[SOFTWARE_PARADIGM] ([ID])
GO
ALTER TABLE [dbo].[APPLICATION_BELONGS_TO_PARADIGM] CHECK CONSTRAINT [FK_PARADIGM_ID]
GO
ALTER TABLE [dbo].[APPLICATION_BELONGS_TO_SUBJECT_AREA]  WITH CHECK ADD  CONSTRAINT [FK_APPLICATION_BELONGS_TO_SUBJECT_AREA_APPLICATION_BELONGS_TO_SUBJECT_AREA_ID] FOREIGN KEY([SUBJECT_AREA_ID])
REFERENCES [dbo].[SUBJECT_AREA] ([ID])
GO
ALTER TABLE [dbo].[APPLICATION_BELONGS_TO_SUBJECT_AREA] CHECK CONSTRAINT [FK_APPLICATION_BELONGS_TO_SUBJECT_AREA_APPLICATION_BELONGS_TO_SUBJECT_AREA_ID]
GO
ALTER TABLE [dbo].[APPLICATION_BELONGS_TO_SUBJECT_AREA]  WITH CHECK ADD  CONSTRAINT [FK_APPLICATION_BELONGS_TO_SUBJECT_AREA_APPLICATION_ID] FOREIGN KEY([APPLICATION_ID])
REFERENCES [dbo].[APPLICATION] ([ID])
GO
ALTER TABLE [dbo].[APPLICATION_BELONGS_TO_SUBJECT_AREA] CHECK CONSTRAINT [FK_APPLICATION_BELONGS_TO_SUBJECT_AREA_APPLICATION_ID]
GO
ALTER TABLE [dbo].[APPLICATION_HAS_SOFTWARE_FEATURE]  WITH CHECK ADD  CONSTRAINT [FK_APPLICATION_HAS_SOFTWARE_FEATURE_APPLICATION_ID] FOREIGN KEY([APPLICATION_ID])
REFERENCES [dbo].[APPLICATION] ([ID])
GO
ALTER TABLE [dbo].[APPLICATION_HAS_SOFTWARE_FEATURE] CHECK CONSTRAINT [FK_APPLICATION_HAS_SOFTWARE_FEATURE_APPLICATION_ID]
GO
ALTER TABLE [dbo].[APPLICATION_HAS_SOFTWARE_FEATURE]  WITH CHECK ADD  CONSTRAINT [FK_APPLICATION_HAS_SOFTWARE_FEATURE_FEATURE_ID] FOREIGN KEY([SOFTWARE_FEATURE_ID])
REFERENCES [dbo].[SOFTWARE_FEATURE] ([ID])
GO
ALTER TABLE [dbo].[APPLICATION_HAS_SOFTWARE_FEATURE] CHECK CONSTRAINT [FK_APPLICATION_HAS_SOFTWARE_FEATURE_FEATURE_ID]
GO
ALTER TABLE [dbo].[APPLICATION_USES_LANGUAGE]  WITH CHECK ADD  CONSTRAINT [FK_APPLICATION_USES_LANGUAGE_APPLICATION] FOREIGN KEY([APPLICATION_ID])
REFERENCES [dbo].[APPLICATION] ([ID])
GO
ALTER TABLE [dbo].[APPLICATION_USES_LANGUAGE] CHECK CONSTRAINT [FK_APPLICATION_USES_LANGUAGE_APPLICATION]
GO
ALTER TABLE [dbo].[APPLICATION_USES_LANGUAGE]  WITH CHECK ADD  CONSTRAINT [FK_APPLICATION_USES_LANGUAGE_LANGUAGE] FOREIGN KEY([LANGUAGE_ID])
REFERENCES [dbo].[LANGUAGE] ([ID])
GO
ALTER TABLE [dbo].[APPLICATION_USES_LANGUAGE] CHECK CONSTRAINT [FK_APPLICATION_USES_LANGUAGE_LANGUAGE]
GO
ALTER TABLE [dbo].[APPLICATION_USES_SYSTEM_STRUCTURE]  WITH CHECK ADD  CONSTRAINT [FK_APPLICATION_USES_SYSTEM_STRUCTURE_APPLICATION] FOREIGN KEY([APPLICATION_ID])
REFERENCES [dbo].[APPLICATION] ([ID])
GO
ALTER TABLE [dbo].[APPLICATION_USES_SYSTEM_STRUCTURE] CHECK CONSTRAINT [FK_APPLICATION_USES_SYSTEM_STRUCTURE_APPLICATION]
GO
ALTER TABLE [dbo].[APPLICATION_USES_SYSTEM_STRUCTURE]  WITH CHECK ADD  CONSTRAINT [FK_APPLICATION_USES_SYSTEM_STRUCTURE_SYSTEM_STRUCTURE] FOREIGN KEY([SYSTEM_STRUCTURE_ID])
REFERENCES [dbo].[SYSTEM_STRUCTURE] ([ID])
GO
ALTER TABLE [dbo].[APPLICATION_USES_SYSTEM_STRUCTURE] CHECK CONSTRAINT [FK_APPLICATION_USES_SYSTEM_STRUCTURE_SYSTEM_STRUCTURE]
GO
ALTER TABLE [dbo].[APPROACH_HAS_TECHNIQUE]  WITH CHECK ADD  CONSTRAINT [FK_APPROACH_HAS_TECHNIQUE_APPROACH] FOREIGN KEY([APPROACH_ID])
REFERENCES [dbo].[APPROACH] ([ID])
GO
ALTER TABLE [dbo].[APPROACH_HAS_TECHNIQUE] CHECK CONSTRAINT [FK_APPROACH_HAS_TECHNIQUE_APPROACH]
GO
ALTER TABLE [dbo].[APPROACH_HAS_TECHNIQUE]  WITH CHECK ADD  CONSTRAINT [FK_APPROACH_HAS_TECHNIQUE_TECHNIQUE] FOREIGN KEY([TECHNIQUE_ID])
REFERENCES [dbo].[TECHNIQUE] ([ID])
GO
ALTER TABLE [dbo].[APPROACH_HAS_TECHNIQUE] CHECK CONSTRAINT [FK_APPROACH_HAS_TECHNIQUE_TECHNIQUE]
GO
ALTER TABLE [dbo].[APPROACH_RELATED_STRUCTURE]  WITH CHECK ADD  CONSTRAINT [FK_APPROACH_RELATED_STRUCTURE_APPROACH] FOREIGN KEY([APPROACH_ID])
REFERENCES [dbo].[APPROACH] ([ID])
GO
ALTER TABLE [dbo].[APPROACH_RELATED_STRUCTURE] CHECK CONSTRAINT [FK_APPROACH_RELATED_STRUCTURE_APPROACH]
GO
ALTER TABLE [dbo].[APPROACH_RELATED_STRUCTURE]  WITH CHECK ADD  CONSTRAINT [FK_APPROACH_RELATED_STRUCTURE_SYSTEM_STRUCTURE] FOREIGN KEY([SYSTEM_STRUCTURE_ID])
REFERENCES [dbo].[SYSTEM_STRUCTURE] ([ID])
GO
ALTER TABLE [dbo].[APPROACH_RELATED_STRUCTURE] CHECK CONSTRAINT [FK_APPROACH_RELATED_STRUCTURE_SYSTEM_STRUCTURE]
GO
ALTER TABLE [dbo].[CONSTRUCTION_PRACTICE_FOLLOWS_STRATEGY]  WITH CHECK ADD  CONSTRAINT [FK_CONSTRUCTION_PRACTICE_FOLLOWS_STRATEGY_CONSTRUCTION_PRACTICE] FOREIGN KEY([CONSTRUCTION_PRACTICE_ID])
REFERENCES [dbo].[CONSTRUCTION_PRACTICE] ([ID])
GO
ALTER TABLE [dbo].[CONSTRUCTION_PRACTICE_FOLLOWS_STRATEGY] CHECK CONSTRAINT [FK_CONSTRUCTION_PRACTICE_FOLLOWS_STRATEGY_CONSTRUCTION_PRACTICE]
GO
ALTER TABLE [dbo].[CONSTRUCTION_PRACTICE_FOLLOWS_STRATEGY]  WITH CHECK ADD  CONSTRAINT [FK_CONSTRUCTION_PRACTICE_FOLLOWS_STRATEGY_STRATEGY] FOREIGN KEY([STRATEGY_ID])
REFERENCES [dbo].[STRATEGY] ([ID])
GO
ALTER TABLE [dbo].[CONSTRUCTION_PRACTICE_FOLLOWS_STRATEGY] CHECK CONSTRAINT [FK_CONSTRUCTION_PRACTICE_FOLLOWS_STRATEGY_STRATEGY]
GO
ALTER TABLE [dbo].[CONSTRUCTION_PRACTICE_HAS_METHOD]  WITH CHECK ADD  CONSTRAINT [FK_CONSTRUCTION_PRACTICE_HAS_METHOD_CONSTRUCTION_PRACTICE] FOREIGN KEY([CONSTRUCTION_PRACTICE_ID])
REFERENCES [dbo].[CONSTRUCTION_PRACTICE] ([ID])
GO
ALTER TABLE [dbo].[CONSTRUCTION_PRACTICE_HAS_METHOD] CHECK CONSTRAINT [FK_CONSTRUCTION_PRACTICE_HAS_METHOD_CONSTRUCTION_PRACTICE]
GO
ALTER TABLE [dbo].[CONSTRUCTION_PRACTICE_HAS_METHOD]  WITH CHECK ADD  CONSTRAINT [FK_CONSTRUCTION_PRACTICE_HAS_METHOD_METHOD] FOREIGN KEY([METHOD_ID])
REFERENCES [dbo].[METHOD] ([ID])
GO
ALTER TABLE [dbo].[CONSTRUCTION_PRACTICE_HAS_METHOD] CHECK CONSTRAINT [FK_CONSTRUCTION_PRACTICE_HAS_METHOD_METHOD]
GO
ALTER TABLE [dbo].[LANGUAGE_HAS_SECURITY_TOOL]  WITH CHECK ADD  CONSTRAINT [FK_LANGUAGE_HAS_SECURITY_TOOL_LANGUAGE] FOREIGN KEY([LANGUAGE_ID])
REFERENCES [dbo].[LANGUAGE] ([ID])
GO
ALTER TABLE [dbo].[LANGUAGE_HAS_SECURITY_TOOL] CHECK CONSTRAINT [FK_LANGUAGE_HAS_SECURITY_TOOL_LANGUAGE]
GO
ALTER TABLE [dbo].[LANGUAGE_HAS_SECURITY_TOOL]  WITH CHECK ADD  CONSTRAINT [FK_LANGUAGE_HAS_SECURITY_TOOL_SECURITY_TOOL] FOREIGN KEY([SECURITY_TOOL])
REFERENCES [dbo].[SECURITY_TOOL] ([ID])
GO
ALTER TABLE [dbo].[LANGUAGE_HAS_SECURITY_TOOL] CHECK CONSTRAINT [FK_LANGUAGE_HAS_SECURITY_TOOL_SECURITY_TOOL]
GO
ALTER TABLE [dbo].[LANGUAGE_PROVIDES_TECHNOLOGY]  WITH CHECK ADD  CONSTRAINT [FK_LANGUAGE_PROVIDES_TECHNOLOGY_LANGUAGE] FOREIGN KEY([LANGUAGE_ID])
REFERENCES [dbo].[LANGUAGE] ([ID])
GO
ALTER TABLE [dbo].[LANGUAGE_PROVIDES_TECHNOLOGY] CHECK CONSTRAINT [FK_LANGUAGE_PROVIDES_TECHNOLOGY_LANGUAGE]
GO
ALTER TABLE [dbo].[LANGUAGE_PROVIDES_TECHNOLOGY]  WITH CHECK ADD  CONSTRAINT [FK_LANGUAGE_PROVIDES_TECHNOLOGY_TECHNOLOGY] FOREIGN KEY([TECHNOLOGY_ID])
REFERENCES [dbo].[TECHNOLOGY] ([ID])
GO
ALTER TABLE [dbo].[LANGUAGE_PROVIDES_TECHNOLOGY] CHECK CONSTRAINT [FK_LANGUAGE_PROVIDES_TECHNOLOGY_TECHNOLOGY]
GO
ALTER TABLE [dbo].[MECHANISM_UTILIZES_SECURITY_TOOL]  WITH CHECK ADD  CONSTRAINT [FK_MECHANISM_UTILIZES_SECURITY_TOOL_MECHANISM] FOREIGN KEY([MECHANISM_ID])
REFERENCES [dbo].[MECHANISM] ([ID])
GO
ALTER TABLE [dbo].[MECHANISM_UTILIZES_SECURITY_TOOL] CHECK CONSTRAINT [FK_MECHANISM_UTILIZES_SECURITY_TOOL_MECHANISM]
GO
ALTER TABLE [dbo].[MECHANISM_UTILIZES_SECURITY_TOOL]  WITH CHECK ADD  CONSTRAINT [FK_MECHANISM_UTILIZES_SECURITY_TOOL_SECURITY_TOOL] FOREIGN KEY([SECURITY_TOOL_ID])
REFERENCES [dbo].[SECURITY_TOOL] ([ID])
GO
ALTER TABLE [dbo].[MECHANISM_UTILIZES_SECURITY_TOOL] CHECK CONSTRAINT [FK_MECHANISM_UTILIZES_SECURITY_TOOL_SECURITY_TOOL]
GO
ALTER TABLE [dbo].[METHOD_HAS_MECHANISM]  WITH CHECK ADD  CONSTRAINT [FK_METHOD_HAS_MECHANISM_MECHANISM] FOREIGN KEY([MECHANISM_ID])
REFERENCES [dbo].[MECHANISM] ([ID])
GO
ALTER TABLE [dbo].[METHOD_HAS_MECHANISM] CHECK CONSTRAINT [FK_METHOD_HAS_MECHANISM_MECHANISM]
GO
ALTER TABLE [dbo].[METHOD_HAS_MECHANISM]  WITH CHECK ADD  CONSTRAINT [FK_METHOD_HAS_MECHANISM_METHOD] FOREIGN KEY([METHOD_ID])
REFERENCES [dbo].[METHOD] ([ID])
GO
ALTER TABLE [dbo].[METHOD_HAS_MECHANISM] CHECK CONSTRAINT [FK_METHOD_HAS_MECHANISM_METHOD]
GO
ALTER TABLE [dbo].[METHOD_RELATED_LANGUAGE]  WITH CHECK ADD  CONSTRAINT [FK_METHOD_RELATED_LANGUAGE_LANGUAGE] FOREIGN KEY([LANGUAGE_ID])
REFERENCES [dbo].[LANGUAGE] ([ID])
GO
ALTER TABLE [dbo].[METHOD_RELATED_LANGUAGE] CHECK CONSTRAINT [FK_METHOD_RELATED_LANGUAGE_LANGUAGE]
GO
ALTER TABLE [dbo].[METHOD_RELATED_LANGUAGE]  WITH CHECK ADD  CONSTRAINT [FK_METHOD_RELATED_LANGUAGE_METHOD] FOREIGN KEY([METHOD_ID])
REFERENCES [dbo].[METHOD] ([ID])
GO
ALTER TABLE [dbo].[METHOD_RELATED_LANGUAGE] CHECK CONSTRAINT [FK_METHOD_RELATED_LANGUAGE_METHOD]
GO
ALTER TABLE [dbo].[SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS_SECURITY_ERROR] FOREIGN KEY([SECURITY_ERROR_ID])
REFERENCES [dbo].[SECURITY_ERROR] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS] CHECK CONSTRAINT [FK_SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS_SECURITY_ERROR]
GO
ALTER TABLE [dbo].[SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS_SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS] FOREIGN KEY([SOFTWARE_WEAKNESS_ID])
REFERENCES [dbo].[SOFTWARE_WEAKNESS] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS] CHECK CONSTRAINT [FK_SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS_SECURITY_ERROR_CAUSES_SOFTWARE_WEAKNESS]
GO
ALTER TABLE [dbo].[SECURITY_ERROR_MITIGATED_BY_CONSTRUCTION_PRACTICE]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_ERROR_MITIGATED_BY_CONSTRUCTION_PRACTICE_CONSTRUCTION_PRACTICE_ID] FOREIGN KEY([CONSTRUCTION_PRACTICE_ID])
REFERENCES [dbo].[CONSTRUCTION_PRACTICE] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_ERROR_MITIGATED_BY_CONSTRUCTION_PRACTICE] CHECK CONSTRAINT [FK_SECURITY_ERROR_MITIGATED_BY_CONSTRUCTION_PRACTICE_CONSTRUCTION_PRACTICE_ID]
GO
ALTER TABLE [dbo].[SECURITY_ERROR_MITIGATED_BY_CONSTRUCTION_PRACTICE]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_ERROR_MITIGATED_BY_CONSTRUCTION_PRACTICE_SECURITY_ERROR_ID] FOREIGN KEY([SECURITY_ERROR_ID])
REFERENCES [dbo].[SECURITY_ERROR] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_ERROR_MITIGATED_BY_CONSTRUCTION_PRACTICE] CHECK CONSTRAINT [FK_SECURITY_ERROR_MITIGATED_BY_CONSTRUCTION_PRACTICE_SECURITY_ERROR_ID]
GO
ALTER TABLE [dbo].[SECURITY_ERROR_SPOTTED_BY_VERIFICATION_PRACTICE]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_ERROR_SPOTTED_BY_VERIFICATION_PRACTICE_SECURITY_ERROR_ID] FOREIGN KEY([SECURITY_ERROR_ID])
REFERENCES [dbo].[SECURITY_ERROR] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_ERROR_SPOTTED_BY_VERIFICATION_PRACTICE] CHECK CONSTRAINT [FK_SECURITY_ERROR_SPOTTED_BY_VERIFICATION_PRACTICE_SECURITY_ERROR_ID]
GO
ALTER TABLE [dbo].[SECURITY_ERROR_SPOTTED_BY_VERIFICATION_PRACTICE]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_ERROR_SPOTTED_BY_VERIFICATION_PRACTICE_VERIFICATION_PRACTICE_ID] FOREIGN KEY([VERIFICATION_PRACTICE_ID])
REFERENCES [dbo].[VERIFICATION_PRACTICE] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_ERROR_SPOTTED_BY_VERIFICATION_PRACTICE] CHECK CONSTRAINT [FK_SECURITY_ERROR_SPOTTED_BY_VERIFICATION_PRACTICE_VERIFICATION_PRACTICE_ID]
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_ASSOCIATED_SECURITY_ERROR]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_REQUIREMENT_ASSOCIATED_SECURITY_ERROR_SECURITY_ERROR_ID] FOREIGN KEY([SECURITY_ERROR_ID])
REFERENCES [dbo].[SECURITY_ERROR] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_ASSOCIATED_SECURITY_ERROR] CHECK CONSTRAINT [FK_SECURITY_REQUIREMENT_ASSOCIATED_SECURITY_ERROR_SECURITY_ERROR_ID]
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_ASSOCIATED_SECURITY_ERROR]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_REQUIREMENT_ASSOCIATED_SECURITY_ERROR_SECURITY_REQUIREMENT_ID] FOREIGN KEY([SECURITY_REQUIREMENT_ID])
REFERENCES [dbo].[SECURITY_REQUIREMENT] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_ASSOCIATED_SECURITY_ERROR] CHECK CONSTRAINT [FK_SECURITY_REQUIREMENT_ASSOCIATED_SECURITY_ERROR_SECURITY_REQUIREMENT_ID]
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_CONSTRUCTION_PRACTICE]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_REQUIREMENT_FOLLOWED_BY_CONSTRUCTION_PRACTICE_CONSTRUCTION_PRACTICE_ID] FOREIGN KEY([CONSTRUCTION_PRACTICE_ID])
REFERENCES [dbo].[CONSTRUCTION_PRACTICE] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_CONSTRUCTION_PRACTICE] CHECK CONSTRAINT [FK_SECURITY_REQUIREMENT_FOLLOWED_BY_CONSTRUCTION_PRACTICE_CONSTRUCTION_PRACTICE_ID]
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_CONSTRUCTION_PRACTICE]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_REQUIREMENT_FOLLOWED_BY_CONSTRUCTION_PRACTICE_SECURITY_REQUIREMENT_ID] FOREIGN KEY([SECURITY_REQUIREMENT_ID])
REFERENCES [dbo].[SECURITY_REQUIREMENT] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_CONSTRUCTION_PRACTICE] CHECK CONSTRAINT [FK_SECURITY_REQUIREMENT_FOLLOWED_BY_CONSTRUCTION_PRACTICE_SECURITY_REQUIREMENT_ID]
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_VERIFICATION_PRACTICE]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_REQUIREMENT_FOLLOWED_BY_VERIFICATION_PRACTICE_SECURITY_REQUIREMENT_ID] FOREIGN KEY([SECURITY_REQUIREMENT_ID])
REFERENCES [dbo].[SECURITY_REQUIREMENT] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_VERIFICATION_PRACTICE] CHECK CONSTRAINT [FK_SECURITY_REQUIREMENT_FOLLOWED_BY_VERIFICATION_PRACTICE_SECURITY_REQUIREMENT_ID]
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_VERIFICATION_PRACTICE]  WITH CHECK ADD  CONSTRAINT [FK_SECURITY_REQUIREMENT_FOLLOWED_BY_VERIFICATION_PRACTICE_VERIFICATION_PRACTICE_ID] FOREIGN KEY([VERIFICATION_PRACTICE_ID])
REFERENCES [dbo].[VERIFICATION_PRACTICE] ([ID])
GO
ALTER TABLE [dbo].[SECURITY_REQUIREMENT_FOLLOWED_BY_VERIFICATION_PRACTICE] CHECK CONSTRAINT [FK_SECURITY_REQUIREMENT_FOLLOWED_BY_VERIFICATION_PRACTICE_VERIFICATION_PRACTICE_ID]
GO
ALTER TABLE [dbo].[SOFTWARE_FEATURE_HAS_CONSTRUCTION_PRACTICE]  WITH CHECK ADD  CONSTRAINT [FK_SOFTWARE_FEATURE_HAS_CONTRUCTION_PRACTICE_CONSTRUCTION_PRACTICE] FOREIGN KEY([CONSTRUCTION_PRACTICE_ID])
REFERENCES [dbo].[CONSTRUCTION_PRACTICE] ([ID])
GO
ALTER TABLE [dbo].[SOFTWARE_FEATURE_HAS_CONSTRUCTION_PRACTICE] CHECK CONSTRAINT [FK_SOFTWARE_FEATURE_HAS_CONTRUCTION_PRACTICE_CONSTRUCTION_PRACTICE]
GO
ALTER TABLE [dbo].[SOFTWARE_FEATURE_HAS_CONSTRUCTION_PRACTICE]  WITH CHECK ADD  CONSTRAINT [FK_SOFTWARE_FEATURE_HAS_CONTRUCTION_PRACTICE_SOFTWARE_FEATURE] FOREIGN KEY([SOFTWARE_FEATURE_ID])
REFERENCES [dbo].[SOFTWARE_FEATURE] ([ID])
GO
ALTER TABLE [dbo].[SOFTWARE_FEATURE_HAS_CONSTRUCTION_PRACTICE] CHECK CONSTRAINT [FK_SOFTWARE_FEATURE_HAS_CONTRUCTION_PRACTICE_SOFTWARE_FEATURE]
GO
ALTER TABLE [dbo].[SOFTWARE_FEATURE_HAS_SECURITY_REQUIREMENT]  WITH CHECK ADD  CONSTRAINT [FK_SOFTWARE_FEATURE_HAS_SECURITY_REQUIREMENT_SECURITY_REQUIREMENT_ID] FOREIGN KEY([SECURITY_REQUIREMENT_ID])
REFERENCES [dbo].[SECURITY_REQUIREMENT] ([ID])
GO
ALTER TABLE [dbo].[SOFTWARE_FEATURE_HAS_SECURITY_REQUIREMENT] CHECK CONSTRAINT [FK_SOFTWARE_FEATURE_HAS_SECURITY_REQUIREMENT_SECURITY_REQUIREMENT_ID]
GO
ALTER TABLE [dbo].[SOFTWARE_FEATURE_HAS_SECURITY_REQUIREMENT]  WITH CHECK ADD  CONSTRAINT [FK_SOFTWARE_FEATURE_HAS_SECURITY_REQUIREMENT_SOFTWARE_FEATURE_ID] FOREIGN KEY([SOFTWARE_FEATURE_ID])
REFERENCES [dbo].[SOFTWARE_FEATURE] ([ID])
GO
ALTER TABLE [dbo].[SOFTWARE_FEATURE_HAS_SECURITY_REQUIREMENT] CHECK CONSTRAINT [FK_SOFTWARE_FEATURE_HAS_SECURITY_REQUIREMENT_SOFTWARE_FEATURE_ID]
GO
ALTER TABLE [dbo].[SOFTWARE_PARADIGM_HAS_LANGUAGE_OPTION]  WITH CHECK ADD  CONSTRAINT [FK_SOFTWARE_PARADIGM_HAS_LANGUAGE_OPTION_LANGUAGE] FOREIGN KEY([LANGUAGE_ID])
REFERENCES [dbo].[LANGUAGE] ([ID])
GO
ALTER TABLE [dbo].[SOFTWARE_PARADIGM_HAS_LANGUAGE_OPTION] CHECK CONSTRAINT [FK_SOFTWARE_PARADIGM_HAS_LANGUAGE_OPTION_LANGUAGE]
GO
ALTER TABLE [dbo].[SOFTWARE_PARADIGM_HAS_LANGUAGE_OPTION]  WITH CHECK ADD  CONSTRAINT [FK_SOFTWARE_PARADIGM_HAS_LANGUAGE_OPTION_SOFTWARE_PARADIGM] FOREIGN KEY([SOFTWARE_PARADIGM_ID])
REFERENCES [dbo].[SOFTWARE_PARADIGM] ([ID])
GO
ALTER TABLE [dbo].[SOFTWARE_PARADIGM_HAS_LANGUAGE_OPTION] CHECK CONSTRAINT [FK_SOFTWARE_PARADIGM_HAS_LANGUAGE_OPTION_SOFTWARE_PARADIGM]
GO
ALTER TABLE [dbo].[SOFTWARE_PARADIGM_HAS_SOFTWARE_FEATURE]  WITH CHECK ADD  CONSTRAINT [FK_SOFTWARE_PARADIGM_HAS_SOFTWARE_FEATURE_SOFTWARE_FEATURE_ID] FOREIGN KEY([SOFTWARE_FEATURE_ID])
REFERENCES [dbo].[SOFTWARE_FEATURE] ([ID])
GO
ALTER TABLE [dbo].[SOFTWARE_PARADIGM_HAS_SOFTWARE_FEATURE] CHECK CONSTRAINT [FK_SOFTWARE_PARADIGM_HAS_SOFTWARE_FEATURE_SOFTWARE_FEATURE_ID]
GO
ALTER TABLE [dbo].[SOFTWARE_PARADIGM_HAS_SOFTWARE_FEATURE]  WITH CHECK ADD  CONSTRAINT [FK_SOFTWARE_PARADIGM_HAS_SOFTWARE_FEATURE_SOFTWARE_PARADIGM_ID] FOREIGN KEY([SOFTWARE_PARADIGM_ID])
REFERENCES [dbo].[SOFTWARE_PARADIGM] ([ID])
GO
ALTER TABLE [dbo].[SOFTWARE_PARADIGM_HAS_SOFTWARE_FEATURE] CHECK CONSTRAINT [FK_SOFTWARE_PARADIGM_HAS_SOFTWARE_FEATURE_SOFTWARE_PARADIGM_ID]
GO
ALTER TABLE [dbo].[SUBJECT_AREA_HAS_SOFTWARE_FEATURE]  WITH CHECK ADD  CONSTRAINT [FK_SUBJECT_AREA_HAS_SOFTWARE_FEATURE_SOFTWARE_FEATURE_ID] FOREIGN KEY([SOFTWARE_FEATURE_ID])
REFERENCES [dbo].[SOFTWARE_FEATURE] ([ID])
GO
ALTER TABLE [dbo].[SUBJECT_AREA_HAS_SOFTWARE_FEATURE] CHECK CONSTRAINT [FK_SUBJECT_AREA_HAS_SOFTWARE_FEATURE_SOFTWARE_FEATURE_ID]
GO
ALTER TABLE [dbo].[SUBJECT_AREA_HAS_SOFTWARE_FEATURE]  WITH CHECK ADD  CONSTRAINT [FK_SUBJECT_AREA_HAS_SOFTWARE_FEATURE_SUBJECT_AREA_ID] FOREIGN KEY([SUBJECT_AREA_ID])
REFERENCES [dbo].[SUBJECT_AREA] ([ID])
GO
ALTER TABLE [dbo].[SUBJECT_AREA_HAS_SOFTWARE_FEATURE] CHECK CONSTRAINT [FK_SUBJECT_AREA_HAS_SOFTWARE_FEATURE_SUBJECT_AREA_ID]
GO
ALTER TABLE [dbo].[TECHNIQUE_HAS_SECURITY_TOOL]  WITH CHECK ADD  CONSTRAINT [FK_TECHNIQUE_HAS_SECURITY_TOOL_SECURITY_TOOL] FOREIGN KEY([SECURITY_TOOL_ID])
REFERENCES [dbo].[SECURITY_TOOL] ([ID])
GO
ALTER TABLE [dbo].[TECHNIQUE_HAS_SECURITY_TOOL] CHECK CONSTRAINT [FK_TECHNIQUE_HAS_SECURITY_TOOL_SECURITY_TOOL]
GO
ALTER TABLE [dbo].[TECHNIQUE_HAS_SECURITY_TOOL]  WITH CHECK ADD  CONSTRAINT [FK_TECHNIQUE_HAS_SECURITY_TOOL_TECHNIQUE] FOREIGN KEY([TECHNIQUE_ID])
REFERENCES [dbo].[TECHNIQUE] ([ID])
GO
ALTER TABLE [dbo].[TECHNIQUE_HAS_SECURITY_TOOL] CHECK CONSTRAINT [FK_TECHNIQUE_HAS_SECURITY_TOOL_TECHNIQUE]
GO
ALTER TABLE [dbo].[TECHNOLOGY_HAS_SECURITY_TOOL]  WITH CHECK ADD  CONSTRAINT [FK_TECHNOLOGY_HAS_SECURITY_TOOL_SECURITY_TOOL] FOREIGN KEY([SECURITY_TOOL_ID])
REFERENCES [dbo].[SECURITY_TOOL] ([ID])
GO
ALTER TABLE [dbo].[TECHNOLOGY_HAS_SECURITY_TOOL] CHECK CONSTRAINT [FK_TECHNOLOGY_HAS_SECURITY_TOOL_SECURITY_TOOL]
GO
ALTER TABLE [dbo].[TECHNOLOGY_HAS_SECURITY_TOOL]  WITH CHECK ADD  CONSTRAINT [FK_TECHNOLOGY_HAS_SECURITY_TOOL_TECHNOLOGY_HAS_SECURITY_TOOL] FOREIGN KEY([TECHNOLOGY_ID])
REFERENCES [dbo].[TECHNOLOGY] ([ID])
GO
ALTER TABLE [dbo].[TECHNOLOGY_HAS_SECURITY_TOOL] CHECK CONSTRAINT [FK_TECHNOLOGY_HAS_SECURITY_TOOL_TECHNOLOGY_HAS_SECURITY_TOOL]
GO
ALTER TABLE [dbo].[TECHNOLOGY_RELATED_STRUCTURE]  WITH CHECK ADD  CONSTRAINT [FK_TECHNOLOGY_RELATED_STRUCTURE_SYSTEM_STRUCTURE] FOREIGN KEY([SYSTEM_STRUCTURE_ID])
REFERENCES [dbo].[SYSTEM_STRUCTURE] ([ID])
GO
ALTER TABLE [dbo].[TECHNOLOGY_RELATED_STRUCTURE] CHECK CONSTRAINT [FK_TECHNOLOGY_RELATED_STRUCTURE_SYSTEM_STRUCTURE]
GO
ALTER TABLE [dbo].[TECHNOLOGY_RELATED_STRUCTURE]  WITH CHECK ADD  CONSTRAINT [FK_TECHNOLOGY_RELATED_STRUCTURE_TECHNOLOGY] FOREIGN KEY([TECHNOLOGY_ID])
REFERENCES [dbo].[TECHNOLOGY] ([ID])
GO
ALTER TABLE [dbo].[TECHNOLOGY_RELATED_STRUCTURE] CHECK CONSTRAINT [FK_TECHNOLOGY_RELATED_STRUCTURE_TECHNOLOGY]
GO
ALTER TABLE [dbo].[VERIFICATION_PRACTICE_HAS_APPROACH]  WITH CHECK ADD  CONSTRAINT [FK_VERIFICATION_PRACTICE_HAS_APPROACH_APPROACH] FOREIGN KEY([APPROACH_ID])
REFERENCES [dbo].[APPROACH] ([ID])
GO
ALTER TABLE [dbo].[VERIFICATION_PRACTICE_HAS_APPROACH] CHECK CONSTRAINT [FK_VERIFICATION_PRACTICE_HAS_APPROACH_APPROACH]
GO
ALTER TABLE [dbo].[VERIFICATION_PRACTICE_HAS_APPROACH]  WITH CHECK ADD  CONSTRAINT [FK_VERIFICATION_PRACTICE_HAS_APPROACH_VERIFICATION_PRACTICE] FOREIGN KEY([VERIFICATION_PRACTICE_ID])
REFERENCES [dbo].[VERIFICATION_PRACTICE] ([ID])
GO
ALTER TABLE [dbo].[VERIFICATION_PRACTICE_HAS_APPROACH] CHECK CONSTRAINT [FK_VERIFICATION_PRACTICE_HAS_APPROACH_VERIFICATION_PRACTICE]
GO
ALTER TABLE [dbo].[VERIFICATION_PRACTICE_HAS_TECHNIQUE]  WITH CHECK ADD  CONSTRAINT [FK_VERIFICATION_PRACTICE_HAS_TECHNIQUE_TECHNIQUE] FOREIGN KEY([TECHNIQUE_ID])
REFERENCES [dbo].[TECHNIQUE] ([ID])
GO
ALTER TABLE [dbo].[VERIFICATION_PRACTICE_HAS_TECHNIQUE] CHECK CONSTRAINT [FK_VERIFICATION_PRACTICE_HAS_TECHNIQUE_TECHNIQUE]
GO
ALTER TABLE [dbo].[VERIFICATION_PRACTICE_HAS_TECHNIQUE]  WITH CHECK ADD  CONSTRAINT [FK_VERIFICATION_PRACTICE_HAS_TECHNIQUE_VERIFICATION_PRACTICE] FOREIGN KEY([VERIFICATION_PRACTICE_ID])
REFERENCES [dbo].[VERIFICATION_PRACTICE] ([ID])
GO
ALTER TABLE [dbo].[VERIFICATION_PRACTICE_HAS_TECHNIQUE] CHECK CONSTRAINT [FK_VERIFICATION_PRACTICE_HAS_TECHNIQUE_VERIFICATION_PRACTICE]
GO
USE [master]
GO
ALTER DATABASE [SSKMS] SET  READ_WRITE 
GO
